<?php
$title = 'Add new employee';
$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Employee name');

// This provides a default CSS class and placeholder text for the designation element:
$designation = $form->get('designation');
$designation->setAttribute('class', 'form-control');
$designation->setAttribute('placeholder', 'Designation');

$hireDate = $form->get('hire_date');
$hireDate->setAttribute('class', 'form-control');
$hireDate->setAttribute('placeholder', 'Designation');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('employee', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
<div class="form-group">
    <?=$this->formLabel($name)?>
    <?=$this->formElement($name)?>
    <?=$this->formElementErrors()->render($name, ['class' => 'help-block'])?>
</div>

<div class="form-group">
    <?=$this->formLabel($designation)?>
    <?=$this->formElement($designation)?>
    <?=$this->formElementErrors()->render($designation, ['class' => 'help-block'])?>
</div>

<div class="form-group">
    <?=$this->formLabel($hireDate)?>
    <?=$this->formElement($hireDate)?>
    <?=$this->formElementErrors()->render($hireDate, ['class' => 'help-block'])?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();