<?php
$title = 'Employees';
$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<p>
    <a href="<?=$this->url('employee', ['action' => 'add'])?>">Add new employee</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Designation</th>
    <th>Action</th>
</tr>
<?php foreach ($employees as $employee): ?>
    <tr>
        <td><?=$this->escapeHtml($employee->name)?></td>
        <td><?=$this->escapeHtml($employee->designation)?></td>
        <td>
            <a href="<?=$this->url('employee', ['action' => 'edit', 'id' => $employee->id])?>"><button type="button" class="btn btn-success">Edit</button></a>
            <a href="<?=$this->url('employee', ['action' => 'delete', 'id' => $employee->id])?>"><button type="button" class="btn btn-danger">Delete</button></a>
            <a href="<?=$this->url('employee', ['action' => 'salary', 'id' => $employee->id])?>"><button type="button" class="btn btn-info">Salary List</button></a>
        </td>
    </tr>
<?php endforeach;?>
</table>